In [ ]:
import pandas as pd

df_imdb = pd.read_csv('../data/raw/imdb_master_dataset_2020_2025.csv', sep=';')
df_tmdb = pd.read_csv('../data/processed/movie1.csv')

In [ ]:
# Xem data imdb
df_imdb

,id,title,budget,revenue,release_date,genres,vote_avg,vote_cnt,runtime,lang,director,metascore,certificate,pop
0,6723592,Tenet,205000000.0,365309519.0,2020-08-28,Action|Sci-Fi|Thriller,7300,680000,150.0,en,Christopher Nolan,69.0,NaN,680000
1,2948372,Soul,150000000.0,121977511.0,2020-12-25,Animation|Adventure|Comedy,8000,444000,100.0,en,"Pete Docter, Kemp Powers",83.0,NaN,444000
2,8332922,A Quiet Place Part II,61000000.0,297372261.0,2021-05-28,Drama|Horror|Sci-Fi,7200,320000,97.0,en,John Krasinski,71.0,NaN,320000
3,7126948,Wonder Woman 1984,200000000.0,169601036.0,2020-12-18,Action|Adventure|Fantasy,5300,310000,151.0,en,Patty Jenkins,60.0,NaN,310000
4,8936646,Extraction,65000000.0,NaN,2020-04-24,Action|Crime|Thriller,6800,288000,116.0,en,Sam Hargrave,56.0,NaN,288000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5095,34824138,Franklin,NaN,NaN,2025-06-06,Drama,8800,280,97.0,en,Donta Morrison,NaN,NaN,280
5096,29932579,I'm Not Stiller,NaN,NaN,2025-10-30,Drama,6200,279,99.0,en,Stefan Haupt,NaN,NaN,279
5097,35314797,Are We Good?,NaN,NaN,2025-03-11,Documentary|Biography|Comedy,7300,278,97.0,en,Steven Feinartz,69.0,NaN,278
5098,21394182,Goodbye Horses: The Many Lives of Q Lazzarus,NaN,NaN,2025-04-30,Documentary,7400,277,103.0,en,Eva Aridjis Fuentes,NaN,NaN,277
5099,27517474,Gothic Slayers,1000000.0,NaN,2025-03-04,Comedy|Horror,4900,277,101.0,en,Caleb Harris,NaN,NaN,277

In [ ]:
# Xem data tmdb
df_tmdb

,id,title,budget,revenue,release_date,genres,vote_average,vote_count,runtime,original_language,director,top_cast,production_companies,popularity,keywords
0,524369,The Many Saints of Newark,50000000.0,13037403.0,2021-09-22,Crime|Drama,6.304,730,120,en,Alan Taylor,Alessandro Nivola|Leslie Odom Jr.|Michael Gand...,HBO Films|New Line Cinema|Chase Films,12.3028,new jersey|italian american|gangster|prequel|m...
1,524434,Eternals,200000000.0,402064899.0,2021-11-03,Science Fiction|Action|Adventure,6.777,8984,156,en,Chloé Zhao,Gemma Chan|Richard Madden|Angelina Jolie|Salma...,Marvel Studios,12.9431,superhero|supernatural|based on comic|alien|su...
2,1048933,Frates in Inferno,5.0,1.0,2022-12-02,Horror|Fantasy|Thriller|Comedy,0.000,0,10,en,Jayden Pettit,Barkley Dubis|Jayden Pettit,Withered Up Productions|Jayper Productions,0.0453,NaN
3,1573695,The Real Dust Busters,60.0,1.0,2025-01-01,Comedy|Science Fiction|Action|Adventure,10.000,1,60,en,Noah Lee,Noah Lee|Will Pletcher|Joshua Hall|Caleb Beech...,PBHproductions,0.0286,NaN
4,1049574,Darkness of Man,5000000.0,116950000.0,2025-12-18,Action|Crime|Thriller,6.100,5,108,en,James Cullen Bressack,Jean-Claude Van Damme|Emerson Min|Kristanna Lo...,VMI WorldWide|Sandaled Kid Productions,6.0603,"california|interpol|los angeles, california|in..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2854,523781,Words on Bathroom Walls,8000000.0,3151849.0,2020-08-21,Drama|Romance,7.755,652,111,en,Thor Freudenthal,Charlie Plummer|Molly Parker|Walton Goggins|An...,LD Entertainment,2.2509,high school|schizophrenia|narration|cooking|tu...
2855,523977,Summerland,NaN,504296.0,2020-07-24,Drama|Romance,7.500,221,99,en,Jessica Swale,Gemma Arterton|Gugu Mbatha-Raw|Penelope Wilton...,Shoebox Films|Iota Pictures,3.7196,world war ii|evacuation|lesbian relationship|s...
2856,524047,Greenland,34000000.0,52300000.0,2020-07-29,Action|Adventure|Thriller|Science Fiction,7.130,5119,120,en,Ric Roman Waugh,Gerard Butler|Morena Baccarin|David Denman|Hop...,STXfilms|Anton|Thunder Road|G-BASE|Riverstone ...,20.4948,husband wife relationship|panic|kidnapping|loo...
2857,524216,The Mortuary Collection,NaN,107629.0,2020-09-25,Fantasy|Horror,6.721,475,108,en,Ryan Spindell,Clancy Brown|Caitlin Custer|Sarah Hay|Mike C. ...,Trapdoor Pictures|Mountain Path Entertainment|AMP,1.9168,small town|anthology|undertaker|missing person...
2858,1048522,Fremont,3000000.0,600376.0,2023-08-25,Comedy|Drama,6.349,106,92,en,Babak Jalali,Anaita Wali Zada|Jeremy Allen White|Gregg Turk...,Butimar Productions|Extra A Productions|Blue M...,0.6104,immigrant|california|post-traumatic stress dis...

In [ ]:
# Xem thông tin imdb
df_imdb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5100 entries, 0 to 5099
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            5100 non-null   int64
 1   title         5100 non-null   object
 2   budget        3212 non-null   float64
 3   revenue       2841 non-null   float64
 4   release_date  5067 non-null   object
 5   genres        5087 non-null   object
 6   vote_avg      5100 non-null   int64
 7   vote_cnt      5100 non-null   int64
 8   runtime       5082 non-null   float64
 9   lang          5100 non-null   object
 10  director      5090 non-null   object
 11  metascore     2698 non-null   float64
 12  certificate   2432 non-null   object
 13  pop           5100 non-null   int64
dtypes: float64(4), int64(4), object(6)
memory usage: 557.9+ KB

In [ ]:
df_tmdb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2859 entries, 0 to 2858
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    2859 non-null   int64
 1   title                 2859 non-null   object
 2   budget                1961 non-null   float64
 3   revenue               2859 non-null   float64
 4   release_date          2859 non-null   object
 5   genres                2730 non-null   object
 6   vote_average          2859 non-null   float64
 7   vote_count            2859 non-null   int64
 8   runtime               2859 non-null   int64
 9   original_language     2859 non-null   object
 10  director              2769 non-null   object
 11  top_cast              2754 non-null   object
 12  production_companies  2331 non-null   object
 13  popularity            2859 non-null   float64
 14  keywords              2110 non-null   object
dtypes: float64(4), int64(3), object(8)
memory usage: 335.2+ KB

In [ ]:
# Xem số dòng, số
print("Số dòng và số cột imdb: ")
print(df_imdb.shape)

print("Số dòng và số cột tmdb: ")
print(df_tmdb.shape)

Số dòng và số cột imdb:
(5100, 14)
Số dòng và số cột tmdb:
(2859, 15)

In [ ]:
# Xem tên cột imdb
df_imdb.columns

Index(['id', 'title', 'budget', 'revenue', 'release_date', 'genres',
       'vote_avg', 'vote_cnt', 'runtime', 'lang', 'director', 'metascore',
       'certificate', 'pop'],
      dtype='object')

In [ ]:
# Xem tên cột tmdb
df_tmdb.columns

Index(['id', 'title', 'budget', 'revenue', 'release_date', 'genres',
       'vote_average', 'vote_count', 'runtime', 'original_language',
       'director', 'top_cast', 'production_companies', 'popularity',
       'keywords'],
      dtype='object')

In [ ]:
# Cột vote_cnt và pop ở imdb trùng hoàn toàn -> không dùng được cột pop
(df_imdb['vote_cnt'] == df_imdb['pop']).mean()

np.float64(1.0)

In [ ]:
# Đổi tên cột ở imdb
df_imdb = df_imdb.rename(columns={
    'vote_avg': 'vote_average',
    'vote_cnt': 'vote_count',
    'lang': 'original_language',
})

In [ ]:
# Xóa những cột không giống
df_imdb.drop(columns=['metascore', 'certificate', 'pop'], inplace=True)

df_tmdb.drop(columns=['top_cast','production_companies','popularity','keywords'], inplace=True)

In [ ]:
df_imdb.head()

,id,title,budget,revenue,release_date,genres,vote_average,vote_count,runtime,original_language,director
0,6723592,Tenet,205000000.0,365309519.0,2020-08-28,Action|Sci-Fi|Thriller,7300,680000,150.0,en,Christopher Nolan
1,2948372,Soul,150000000.0,121977511.0,2020-12-25,Animation|Adventure|Comedy,8000,444000,100.0,en,"Pete Docter, Kemp Powers"
2,8332922,A Quiet Place Part II,61000000.0,297372261.0,2021-05-28,Drama|Horror|Sci-Fi,7200,320000,97.0,en,John Krasinski
3,7126948,Wonder Woman 1984,200000000.0,169601036.0,2020-12-18,Action|Adventure|Fantasy,5300,310000,151.0,en,Patty Jenkins
4,8936646,Extraction,65000000.0,NaN,2020-04-24,Action|Crime|Thriller,6800,288000,116.0,en,Sam Hargrave

In [ ]:
df_tmdb.head()

,id,title,budget,revenue,release_date,genres,vote_average,vote_count,runtime,original_language,director
0,524369,The Many Saints of Newark,50000000.0,13037403.0,2021-09-22,Crime|Drama,6.304,730,120,en,Alan Taylor
1,524434,Eternals,200000000.0,402064899.0,2021-11-03,Science Fiction|Action|Adventure,6.777,8984,156,en,Chloé Zhao
2,1048933,Frates in Inferno,5.0,1.0,2022-12-02,Horror|Fantasy|Thriller|Comedy,0.000,0,10,en,Jayden Pettit
3,1573695,The Real Dust Busters,60.0,1.0,2025-01-01,Comedy|Science Fiction|Action|Adventure,10.000,1,60,en,Noah Lee
4,1049574,Darkness of Man,5000000.0,116950000.0,2025-12-18,Action|Crime|Thriller,6.100,5,108,en,James Cullen Bressack

In [ ]:
df_imdb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5100 entries, 0 to 5099
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 5100 non-null   int64
 1   title              5100 non-null   object
 2   budget             3212 non-null   float64
 3   revenue            2841 non-null   float64
 4   release_date       5067 non-null   object
 5   genres             5087 non-null   object
 6   vote_average       5100 non-null   int64
 7   vote_count         5100 non-null   int64
 8   runtime            5082 non-null   float64
 9   original_language  5100 non-null   object
 10  director           5090 non-null   object
dtypes: float64(3), int64(3), object(5)
memory usage: 438.4+ KB

In [ ]:
df_tmdb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2859 entries, 0 to 2858
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 2859 non-null   int64
 1   title              2859 non-null   object
 2   budget             1961 non-null   float64
 3   revenue            2859 non-null   float64
 4   release_date       2859 non-null   object
 5   genres             2730 non-null   object
 6   vote_average       2859 non-null   float64
 7   vote_count         2859 non-null   int64
 8   runtime            2859 non-null   int64
 9   original_language  2859 non-null   object
 10  director           2769 non-null   object
dtypes: float64(3), int64(3), object(5)
memory usage: 245.8+ KB

In [ ]:
# Chia cột vote_average imdb cho 1000
df_imdb['vote_average'] = df_imdb['vote_average'] / 1000
df_imdb

,id,title,budget,revenue,release_date,genres,vote_average,vote_count,runtime,original_language,director
0,6723592,Tenet,205000000.0,365309519.0,2020-08-28,Action|Sci-Fi|Thriller,7.3,680000,150.0,en,Christopher Nolan
1,2948372,Soul,150000000.0,121977511.0,2020-12-25,Animation|Adventure|Comedy,8.0,444000,100.0,en,"Pete Docter, Kemp Powers"
2,8332922,A Quiet Place Part II,61000000.0,297372261.0,2021-05-28,Drama|Horror|Sci-Fi,7.2,320000,97.0,en,John Krasinski
3,7126948,Wonder Woman 1984,200000000.0,169601036.0,2020-12-18,Action|Adventure|Fantasy,5.3,310000,151.0,en,Patty Jenkins
4,8936646,Extraction,65000000.0,NaN,2020-04-24,Action|Crime|Thriller,6.8,288000,116.0,en,Sam Hargrave
...,...,...,...,...,...,...,...,...,...,...,...
5095,34824138,Franklin,NaN,NaN,2025-06-06,Drama,8.8,280,97.0,en,Donta Morrison
5096,29932579,I'm Not Stiller,NaN,NaN,2025-10-30,Drama,6.2,279,99.0,en,Stefan Haupt
5097,35314797,Are We Good?,NaN,NaN,2025-03-11,Documentary|Biography|Comedy,7.3,278,97.0,en,Steven Feinartz
5098,21394182,Goodbye Horses: The Many Lives of Q Lazzarus,NaN,NaN,2025-04-30,Documentary,7.4,277,103.0,en,Eva Aridjis Fuentes
5099,27517474,Gothic Slayers,1000000.0,NaN,2025-03-04,Comedy|Horror,4.9,277,101.0,en,Caleb Harris

In [ ]:
# Chuyển runtime về kiểu int, vote_average về float
# runtime → int
df_imdb['runtime'] = pd.to_numeric(df_imdb['runtime'], errors='coerce').astype('Int64')

# vote_average → float (giữ nguyên)
df_imdb['vote_average'] = pd.to_numeric(df_imdb['vote_average'], errors='coerce')

In [ ]:
df_imdb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5100 entries, 0 to 5099
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 5100 non-null   int64
 1   title              5100 non-null   object
 2   budget             3212 non-null   float64
 3   revenue            2841 non-null   float64
 4   release_date       5067 non-null   object
 5   genres             5087 non-null   object
 6   vote_average       5100 non-null   float64
 7   vote_count         5100 non-null   int64
 8   runtime            5082 non-null   Int64
 9   original_language  5100 non-null   object
 10  director           5090 non-null   object
dtypes: Int64(1), float64(3), int64(2), object(5)
memory usage: 443.4+ KB

In [ ]:
df_imdb

,id,title,budget,revenue,release_date,genres,vote_average,vote_count,runtime,original_language,director
0,6723592,Tenet,205000000.0,365309519.0,2020-08-28,Action|Sci-Fi|Thriller,7.3,680000,150,en,Christopher Nolan
1,2948372,Soul,150000000.0,121977511.0,2020-12-25,Animation|Adventure|Comedy,8.0,444000,100,en,"Pete Docter, Kemp Powers"
2,8332922,A Quiet Place Part II,61000000.0,297372261.0,2021-05-28,Drama|Horror|Sci-Fi,7.2,320000,97,en,John Krasinski
3,7126948,Wonder Woman 1984,200000000.0,169601036.0,2020-12-18,Action|Adventure|Fantasy,5.3,310000,151,en,Patty Jenkins
4,8936646,Extraction,65000000.0,NaN,2020-04-24,Action|Crime|Thriller,6.8,288000,116,en,Sam Hargrave
...,...,...,...,...,...,...,...,...,...,...,...
5095,34824138,Franklin,NaN,NaN,2025-06-06,Drama,8.8,280,97,en,Donta Morrison
5096,29932579,I'm Not Stiller,NaN,NaN,2025-10-30,Drama,6.2,279,99,en,Stefan Haupt
5097,35314797,Are We Good?,NaN,NaN,2025-03-11,Documentary|Biography|Comedy,7.3,278,97,en,Steven Feinartz
5098,21394182,Goodbye Horses: The Many Lives of Q Lazzarus,NaN,NaN,2025-04-30,Documentary,7.4,277,103,en,Eva Aridjis Fuentes
5099,27517474,Gothic Slayers,1000000.0,NaN,2025-03-04,Comedy|Horror,4.9,277,101,en,Caleb Harris

In [ ]:
# Gộp 2 file lại
df_all = pd.concat([df_imdb, df_tmdb], ignore_index=True)

In [ ]:
# Xóa duplicate theo title và year
df_all['title'] = df_all['title'].str.lower().str.strip()
df_all['year'] = pd.to_datetime(df_all['release_date'], errors='coerce').dt.year

df_all = df_all.drop_duplicates(subset=['title', 'year'])

In [ ]:
print(df_all.shape)
df_all.head()

(6770, 12)

,id,title,budget,revenue,release_date,genres,vote_average,vote_count,runtime,original_language,director,year
0,6723592,tenet,205000000.0,365309519.0,2020-08-28,Action|Sci-Fi|Thriller,7.3,680000,150,en,Christopher Nolan,2020.0
1,2948372,soul,150000000.0,121977511.0,2020-12-25,Animation|Adventure|Comedy,8.0,444000,100,en,"Pete Docter, Kemp Powers",2020.0
2,8332922,a quiet place part ii,61000000.0,297372261.0,2021-05-28,Drama|Horror|Sci-Fi,7.2,320000,97,en,John Krasinski,2021.0
3,7126948,wonder woman 1984,200000000.0,169601036.0,2020-12-18,Action|Adventure|Fantasy,5.3,310000,151,en,Patty Jenkins,2020.0
4,8936646,extraction,65000000.0,NaN,2020-04-24,Action|Crime|Thriller,6.8,288000,116,en,Sam Hargrave,2020.0

In [ ]:
df_all['title'].duplicated().any()

np.True_

In [ ]:
df_all['title'].duplicated().sum()

np.int64(179)

In [ ]:
df_all[df_all['title'].duplicated(keep=False)].sort_values('title')

,id,title,budget,revenue,release_date,genres,vote_average,vote_count,runtime,original_language,director,year
1728,7405458,a man called otto,50000000.0,113360085.0,2023-01-06,Comedy|Drama,7.500,208000,126,en,Marc Forster,2023.0
7254,937278,a man called otto,50000000.0,108961677.0,2022-12-28,Comedy|Drama,7.752,3484,126,en,Marc Forster,2022.0
5288,1078959,a mistake,NaN,32811.0,2024-09-20,Thriller|Drama,6.200,67,101,en,Christine Jeffs,2024.0
3988,13605284,a mistake,30212.0,96692.0,2025-04-27,Drama|Thriller,5.700,1600,101,en,"Steve Allanson, Christine Jeffs",2025.0
6161,714195,a mouthful of air,NaN,212833.0,2021-10-29,Drama,6.488,81,105,en,Amy Koppelman,2021.0
...,...,...,...,...,...,...,...,...,...,...,...,...
5969,673121,wolf,NaN,199107.0,2021-12-03,Drama,5.200,90,100,en,Nathalie Biancheri,2021.0
6491,777245,women talking,20000000.0,7589419.0,2022-12-23,Drama,6.842,695,104,en,Sarah Polley,2022.0
1784,13669038,women talking,5456531.0,9276103.0,2023-01-27,Drama,6.900,64000,104,en,Sarah Polley,2023.0
2737,15771916,you hurt my feelings,4830788.0,5742597.0,2024-01-26,Comedy|Drama|Romance,6.500,17000,93,en,Nicole Holofcener,2024.0
7038,890215,you hurt my feelings,NaN,5000000.0,2023-05-26,Drama|Comedy|Romance,6.341,179,93,en,Nicole Holofcener,2023.0

In [ ]:
# Xóa duplicate, giữ lại những dòng có nhiều dữ liệu hơn
df1 = df_all.sort_values(by=['budget'], ascending=False)
df1 = df1.drop_duplicates(subset=['title'], keep='first')

In [ ]:
df_all=df1

In [ ]:
df_all.drop(columns=['year'], inplace=True)

In [ ]:
df_all.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6591 entries, 2813 to 7957
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 6591 non-null   int64
 1   title              6591 non-null   object
 2   budget             4361 non-null   float64
 3   revenue            4374 non-null   float64
 4   release_date       6563 non-null   object
 5   genres             6454 non-null   object
 6   vote_average       6591 non-null   float64
 7   vote_count         6591 non-null   int64
 8   runtime            6578 non-null   Int64
 9   original_language  6591 non-null   object
 10  director           6497 non-null   object
dtypes: Int64(1), float64(3), int64(2), object(5)
memory usage: 624.3+ KB

In [ ]:
df_all.to_csv('../data/processed/movie_final.csv', index=False)

In [ ]:
df_all[df_all['genres'] == 'Sci-Fi']

,id,title,budget,revenue,release_date,genres,vote_average,vote_count,runtime,original_language,director
560,8064418,assassin 33 a.d.,5000000.0,NaN,2020-01-24,Sci-Fi,3.0,2500,109,en,Jim Carroll
3913,2375639,south of hope street,2000000.0,NaN,2024-04-18,Sci-Fi,5.9,2100,101,en,Jane Spencer
4137,30579910,night of the skinwalkers,3000.0,NaN,2024-10-01,Sci-Fi,3.1,960,86,en,Michael Szymczyk
633,9812258,g-loc,NaN,NaN,2020-08-11,Sci-Fi,4.5,1900,92,en,Tom Paton
1298,12483708,doors,NaN,NaN,2021-03-23,Sci-Fi,3.6,3800,84,en,"Jeff Desom, Saman Kesh, Dugan O&apos;Neal"
1483,10069166,destination marfa,NaN,NaN,2021-08-03,Sci-Fi,3.8,1700,97,en,Andy Stapp
2267,12774526,after the pandemic,NaN,NaN,2022-03-01,Sci-Fi,3.5,2600,84,en,Richard Lowry
4042,11786386,light,NaN,NaN,2024-04-01,Sci-Fi,2.6,1300,93,en,Matt Woollard
4174,16231344,sentinel,NaN,NaN,2024-03-22,Sci-Fi,2.5,863,90,en,Stefano Milla
4924,39050792,afterlight,NaN,NaN,2025-11-27,Sci-Fi,3.7,484,72,en,"Alison Kohlhardt, Andrew McGee"
5034,38793708,merge,NaN,NaN,2025-10-29,Sci-Fi,3.8,325,77,en,"Béla Baptiste, Dalano Barnes, Richard Fenwick"

In [ ]:
# Chuẩn hóa tên thể
df_all['genres'] = df_all['genres'].replace('Sci-Fi', 'Science Fiction')
df_all['genres'] = df_all['genres'].str.replace('Sci-Fi', 'Science Fiction', regex=False)

In [ ]:
df_all

,id,title,budget,revenue,release_date,genres,vote_average,vote_count,runtime,original_language,director
2813,27688034,the moon,2.800000e+10,5207157.0,2023-08-02,Action|Adventure|Drama,5.800,10000,129,en,Kim Yong-hwa
1137,14810692,escape from mogadishu,2.400000e+10,29902716.0,2021-07-28,Action|Drama|Thriller,7.000,8400,121,en,Ryoo Seung-wan
4535,27433995,jumbo,2.200000e+10,545094.0,2025-08-08,Animation|Adventure|Comedy,7.900,3600,102,en,Ryan Adriandhy
1988,15575470,project wolf hunting,1.200000e+10,3872374.0,2022-09-21,Action|Crime|Horror,6.100,9200,122,en,Hongsun Kim
3835,31254554,wonderland,1.000000e+10,4270030.0,2024-06-05,Drama|Science Fiction,6.200,3000,113,en,"Sharon S. Park, Kim Tae-yong"
...,...,...,...,...,...,...,...,...,...,...,...
7926,521531,followed,NaN,548608.0,2020-06-19,Horror|Mystery|Thriller,5.941,93,96,en,Antoine Le
7933,522098,babyteeth,NaN,989310.0,2020-06-15,Drama|Comedy|Romance,6.877,386,118,en,Shannon Murphy
7934,1570766,2025 world series game 3,NaN,1000000.0,2025-10-27,Documentary,5.000,1,399,en,NaN
7946,522925,dalíland,NaN,497933.0,2022-09-29,History|Drama,5.974,77,97,en,Mary Harron
7957,524216,the mortuary collection,NaN,107629.0,2020-09-25,Fantasy|Horror,6.721,475,108,en,Ryan Spindell

In [ ]:
df_all.to_csv('../data/processed/movie_final.csv', index=False)

In [ ]:
# Xem số lượng thể loại phim
df_all['genres'].str.split('|').explode().nunique()

24

In [ ]:
# Danh sách thể loại phim
df_all['genres'].str.split('|').explode().unique()

array(['Action', 'Adventure', 'Drama', 'Thriller', 'Animation', 'Comedy',
       'Crime', 'Horror', 'Science Fiction', 'Fantasy', 'History', 'War',
       'Romance', 'Biography', 'Mystery', 'Sport', 'Family', 'Musical',
       'Music', 'Western', 'Documentary', nan, 'TV Movie', 'News',
       'Talk-Show'], dtype=object)

In [ ]:
# Số lượng từng thể loại
df_all['genres'].str.split('|').explode().value_counts()

genres
Drama              2767
Comedy             1746
Thriller           1298
Horror             1288
Action             1124
Documentary         910
Crime               755
Adventure           672
Mystery             667
Romance             609
Biography           411
Science Fiction     389
Fantasy             330
Animation           327
Music               280
History             278
Family              271
Sport               119
War                  89
Western              46
Musical              44
TV Movie             13
News                  1
Talk-Show             1
Name: count, dtype: int64